### PR TITLE
Fixes & reformat

### PR DESCRIPTION
**Pull request by MisterDA**
This PR has commits that are mostly sane, to clean up the build process. Headers names are now uniform, inclusion use quotes `"` for project headers and angle brackets for standard libraries. CMake now enforces C++11, and adds compiler warnings. CMake can also be used to build packages for all OS, and I started to work on that.

Commit 0c54dd7 fixes all warnings I encountered, and also simplifies the code.

The controversial commit is e1498d5 that formats the whole project according to the [Google C++ Style Guide][1], using the `clang-format` tool. IMO, this document should be loosely followed, but the style guide is useful to enforce uniform coding style across the project (for instance, many files were using mixed indentation with tabs and space).
This commit can be dropped if too controversial, the main problem is that it is impossible after that to follow the history line-by-line (git blame) because it effectively rewrites all the files. If you prefer to chose another style, this is easy. I don’t want to spend time creating a style that follows as much as possible NeneQuest current state, because NeneQuest is not consistent.

```sh
cd nenequest
clang-format -i src/**/*.cpp headers/**/*.hpp
```
[1]: https://google.github.io/styleguide/cppguide.html

### CODE REVIEW

**Comment by eikofee** [comment]
I'm quite surprised you tried to improve the current state of the coding style we have there. I actually started to purge and rework a lot of the stuff we made because we took way too complexes approaches for a such a simple project, and add to this the fact that some of us were using C++ for the first time (at least it was my case), it is now currently very difficult to dig into and improve it.

I'll take a look at your changes as soon as possible.

**Comment by eikofee** [comment]
Okay, took a brief look into it. I'm okay with the Google coding style guidelines, but I guess we can use any sort of coding style guideline as long as it looks somewhat clean. Instead of using an external software, I think it should be better to configure our respective IDEs with the said guidelines, to avoid that history rewrite you mentioned.

The CMake update is nice. I redid it on my end but since I'm absolutely not familiar with it, your input is more than welcome, thanks for that.

However I have purged a lot of the files you worked on, so normally I'd keep this PR into a separate branch and merge it on other actives branches, but since my edits are only local on my machine because others were busy when I got back into the project, there's no really use in keeping this PR aside imo.

I'm fine with this branch being merged on master. I'll wait a bit for others to comment on it too. I don't know if they tried to also rework on the project.

cc @engboris @KostiaChardonnet @hokolomopo

**Comment by engboris** [comment]
Salut

**Comment by KostiaChardonnet** [comment]
I agree with the convention except for the fact that * and & are close to the type instead of the parameter. For example in dragon.cpp, line 176 you have 

```Cpp
void Dragon::draw(sf::RenderTarget& target, sf::RenderStates states)
```
Instead of

```Cpp
void Dragon::draw(sf::RenderTarget &target, sf::RenderStates states)
```


Aside from that I'm fine with the PR (with my previous commit).

**Comment by MisterDA** [comment]
Sorry for the force-push.
I just integrated some remarks made privately by @KostiaChardonnet into the relevant commits.
There were some CMake fixes, and the alignment of pointer stars and references to right.

**Comment by MisterDA** [comment]
The PR has problems with the order of headers. Please, do not merge for the moment.

**Comment by eikofee** [comment]
I was fine with `type* param` instead of `type *param` lol.

Also @KostiaChardonnet , you shouldn't push on someone else's PR (and even less force-push on it), because it can breaks the history of the PR like any git repo, but also **because it's not your work**. Instead, you can make comments on lines when reviewing a PR, or wait until the PR is merged on the main project.

**Comment by MisterDA** [comment]
> because it's not your work

For @KostiaChardonnet's defence, we were together and I was curious to see if he could actually force-push to the branch. But you’re right in the general case.

> The PR has problems with the order of headers. 

Fixed.

>> I agree with the convention except for the fact that * and & are close to the type instead of the parameter.
>
> I was fine with type* param instead of type *param lol.

For me, the problem with left-align appears with multiple declarations:
```cpp
int* a, b, c;
int *a, *b, *c;
```
In that case, left-align is not desirable. But I would say that `*` and `&` should be part of the type… My preference goes to right-align.

> Please, do not merge for the moment.

Sorry for the multiple force-pushes. I’m now more confident that the PR is good to go.

There is still one thing missing: NeneQuest is not able to load assets and configuration from a given path, defined at compilation or run time, so the CMake installer does put the files in sensible locations, but NeneQuest can’t use them.

**Comment by eikofee** [comment]
Okay, I'll try to build with both cmake and windows's cpp compiler when I'm back home and merge the PR if it works.

**Comment by eikofee** [comment]
okay so my Visual Studio environment can compile the program without any inch.
 However, CMake isn't working properly, since it tries to use the x64 compiler with my 32bit SFML library. I tried to edit `CMakeList.txt` to specify a Win32|Debug target but without real success. I managed to generate the whole Visual Studio solution once with a Win32|Debug configuration but it couldn't compile properly, and I *think* I used a default CMake configuration for it.

I didn't tried to make it work on WSL yet.

**Comment by KostiaChardonnet** [comment]
I believe you are the only one working on Windows so @MisterDA can't help you. Do you think you can make a OS-dependent build system ?

I have no problems making it work on WSL.

**Comment by eikofee** [comment]
Well, CMake is supposed to be cross-platform, so it creates the building scripts/process for any OS supporting CMake.

**Comment by jmscreation** [comment]
> I believe you are the only one working on Windows so @MisterDA can't help you. Do you think you can make a OS-dependent build system ?

Is this project still alive? I'd be more than happy to contribute a custom build script/toolchain for Windows MinGW-64

**Comment by engboris** [comment]
Hello. Thank you for your interest. This project has been abandoned for a long time. I believe that the main problem was a lack of hierarchy, organisation and anticipation. As a result, the project became more complicated than needed (treating a small and simple project as a big ambitious project with a lot of superficial and extensible structure).
Maybe the best solution would be to start from scratch with something simpler (but keeping some functions and ideas, otherwise it would be a waste). If you're motivated enough you're free to use our resources.

**Comment by jmscreation** [comment]
> Hello. Thank you for your interest. This project has been abandoned for a long time. I believe that the main problem was a lack of hierarchy, organisation and anticipation. As a result, the project became more complicated than needed (treating a small and simple project as a big ambitious project with a lot of superficial and extensible structure).
> Maybe the best solution would be to start from scratch with something simpler (but keeping some functions and ideas, otherwise it would be a waste). If you're motivated enough you're free to use our resources.

Thanks! I would be interested to sift through your existing structure and make major changes if need be. I do understand the concept of keeping it simple, but as some of you had mentioned you were new to C++ at the time, and you can only gain plenty of experience in working on a fun project such as this one.

If you could make a pull request to update the latest changes from _KostiaChardonnet:master_ as they have made additional contributions that haven't made it into the official _master_ branch. I'd really like to just go over it and see if it will be a fun project to work on fwiw.

**Comment by KostiaChardonnet** [comment]
Hi @jmscreation : I actually wanted to finish this project for a while now, I would like to work on it with you if you want. As you said, my branch have a bit more contribution, we can work on it for now, and then pull everything on this repo once its over.

**Comment by jmscreation** [comment]
> Hi @jmscreation : I actually wanted to finish this project for a while now, I would like to work on it with you if you want. As you said, my branch have a bit more contribution, we can work on it for now, and then pull everything on this repo once its over.

@KostiaChardonnet Awesome.
Do you want me to fork yours, or do you want me to directly collaborate on your repository?

Edit: Also, we should get in touch on discord

Here's my discord ID:
https://pastebin.com/FxNJcbaR
I set it for burn after read so other people don't see it

**Comment by MisterDA** [comment]
> I'd be more than happy to contribute a custom build script/toolchain for Windows MinGW-64

CMake should handle that for us.

Good luck ;)

**Comment by jmscreation** [comment]
> > I'd be more than happy to contribute a custom build script/toolchain for Windows MinGW-64
> 
> CMake should handle that for us.
> 
> Good luck ;)

I actually hate CMake quite a bit. I already made a build script for this project that works rather well.
I'm just waiting to hear back from @KostiaChardonnet

**Pull request merged**
