### PR TITLE
Change paths for Linux

### PR DESCRIPTION
**Pull request by byronvanstien**

### CODE REVIEW

**Review by engboris — APPROVED** [review]
Do you want to join our team ?

**Comment by byronvanstien** [comment]
My C++ is pretty terrible, I just went along as errors popped up fixing them when I was trying to compile

**Comment by eikofee** [comment]
So we did 🤔

**Comment by engboris** [comment]
It's fine if you're not experienced. Moreover, we're using a quite simple 2D library.

Feel free to contact us if you're interested. Any comment or idea may be useful. A contribution doesn't necessarily have to be a C++ source code. And if you want to try C++ a bit more, maybe you can learn from us while we learn from you as well.

**Comment by byronvanstien** [comment]
Sounds fine to me, is there any platform you guys communicate on in particular?

**Comment by KostiaChardonnet** [comment]
Hi,

We are using Discord, is that ok with you ? If so, how could I send you the link (in private) to our server ?

**Comment by byronvanstien** [comment]
My Discord is Recchan#0194, send me a friend request

**Pull request merged**
